name: crystal
channels:
  - defaults
  - glotzer
  - malramsay
dependencies:
  - python=3.6
  - ipykernel
  - numba
  - Cython
  - malramsay::sdrun=0.4.7
  - malramsay::sdanalysis=0.5.2
  - malramsay::experi>=0.2.4
  - conda-forge::altair
