name: crystal
channels:
  - defaults
  - conda-forge
  - malramsay
dependencies:
  # Running Simulations
  - python=3.6
  - numba
  - Cython
  - malramsay::sdrun=0.6.3
  - malramsay::sdanalysis=0.7.2
  - malramsay::experi=0.2.11
  # Dev tools
  - pytest
  - mypy
  - black
  - pip
  - isort
  # Interactive analysis
  - ipykernel
  - ipywidgets
  - altair>=2.0
  - nbdime>=1.0
  - matplotlib
  - PhantomJS
  - pillow
  - selenium
  # Writing tools
  - pandoc
  - pip:
    - pandoc-fignos
