name: crystal
channels:
  - defaults
  - glotzer
  - malramsay
dependencies:
  - python=3.6
  - ipykernel
  - numba
  - Cython
  - malramsay::sdrun=0.5.3
  - malramsay::sdanalysis=0.5.5
  - malramsay::experi=0.2.6
  - conda-forge::altair>=2.0
  - conda-forge::nbdime>=1.0
  - conda-forge::ipywidgets
  - PhantomJS
  - pillow
  - selenium
  - pytest
  - mypy
  - black
  - pip
  - pip:
    - blackcellmagic
