name: crystal
channels:
  - defaults
  - glotzer
  - malramsay
dependencies:
  - python=3.6
  - ipykernel
  - numba
  - Cython
  - malramsay::sdrun=0.5.2
  - malramsay::sdanalysis=0.5.4
  - malramsay::experi=0.2.6
  - conda-forge::altair>=2.0
  - conda-forge::nbdime>=1.0
  - conda-forge::ipywidgets
  - pytest
  - mypy
  - black
