name: crystal
channels:
  - defaults
  - glotzer
  - malramsay
dependencies:
  - python=3.6
  - ipykernel
  - numba
  - Cython
  - malramsay::sdrun=0.4.3
  - malramsay::sdanalysis=0.4.12
  - malramsay::experi
  - conda-forge::altair
