name: crystal
channels:
  - defaults
  - glotzer
  - malramsay
dependencies:
  - python=3.6
  - numpy=1.13
  - jupyter
  - malramsay::sdanalysis=0.4.6
  - malramsay::sdrun=0.4.1
  - pip:
    - experi==0.2.1
