name: crystal
channels:
  - defaults
  - glotzer
  - malramsay
dependencies:
  - python=3.6
  - jupyter
  - numba
  - selenium
  - malramsay::sdrun=0.4.3
  - pip:
    - experi==0.2.2
    - sdanalysis==0.4.12
    - git+git://github.com/altair-viz/altair
