name: crystal
channels:
  - defaults
  - conda-forge
  - malramsay
dependencies:
  # Running Simulations
  - python=3.6
  - numba
  - Cython
  - malramsay::sdrun=0.6.0
  - malramsay::sdanalysis=0.5.6
  - malramsay::experi=0.2.8
  # Dev tools
  - pytest
  - mypy
  - black
  - pip
  - pip:
    - blackcellmagic
  # Interactive analysis
  - ipykernel
  - ipywidgets
  - altair>=2.0
  - nbdime>=1.0
  - PhantomJS
  - pillow
  - selenium
