on: [push, pull_request]

name: Linters

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: "3.6"
          architecture: x64
      - name: Install linters
        run: python3 -m pip install mypy flake8 black

      - run: python3 -m black --check src/*
      - run: python3 -m mypy src
      - run: python3 -m flake8 src
