name: Test source code

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Get conda info
        run: $CONDA/bin/conda info

      - name: Install environment using conda
        run: $CONDA/bin/conda env update --name crystal

      - name: Activate conda environment and test commands
        run: |
          source $CONDA/bin/activate crystal
          python3 -m pytest
          dynamics-analysis --help
          crystal-melting --help
          crystal-train-ml --help
          crystal-fluctuations --help
          trajedy --help
          experi --help
          jupytext --help
